<!--

Configuration to whitelist appropriate asset files, for IIS.

This will be autogenerated from File::allowed_extensions via dev/build if one does not exist

-->
<configuration>
	<system.webServer>
		<security>
			<requestFiltering>
				<fileExtensions allowUnlisted="false" applyToWebDAV="true"><% loop AllowedExtensions %>
					<add fileExtension=".$Extension" allowed="true" /><% end_loop %>
				</fileExtensions>
			</requestFiltering>
		</security>
	</system.webServer>
</configuration>
